version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_case_stone
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=dockerPS
      - POSTGRES_DB=case_stone
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: case_stone
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app

    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local